"use strict";
// Inert sample data. This prototype never calls a workspace endpoint.
const topics = [
  {id:"revision",title:"What changed in the proposal?",section:"Revision r04 · proposed update",kind:"Revision inspector",type:"revision",intro:"A new proposal changes the decision path and the evidence shown to reviewers. Inspect the differences before applying it. Applying is not approval.",messages:[{who:"Agent",at:"r04 proposed",text:"I separated the human's consequential choice from my recommendation and linked the journey claim to its supplied source."}]},
  {id:"journey",title:"Where does the reviewer get stuck?",section:"Outcome · review journey",kind:"Outcome and user journey",type:"journey",intro:"The proposed experience moves from a document-first scan to an explicit next action with linked evidence. Does it remove the orientation cost without obscuring the spec?",messages:[{who:"You",at:"r03",text:"Can we see the step between finding a question and reading its source?"},{who:"Agent",at:"r03",text:"The selected topic keeps its conversation in the center and opens its cited evidence in the adjacent canvas. The journey below makes that transition explicit."}]},
  {id:"choice",title:"Should evidence open beside the thread?",section:"Interaction model · context layout",kind:"Choice comparison",type:"choice",intro:"We need one reliable path from a question to its context. Compare a linked side canvas with a separate full-page reading view.",messages:[{who:"Agent",at:"r03",text:"I recommend the linked canvas: it preserves the question while showing the exact evidence. Full reading remains available when the material is dense."}]},
  {id:"diagram",title:"Can the trust boundary stay local?",section:"Architecture · evidence path",kind:"Architecture and flow",type:"diagram",intro:"Published evidence is inert by default. A prototype cannot receive session credentials or call state-changing endpoints.",messages:[{who:"You",at:"r03",text:"Please show where an executable prototype would sit relative to the local workspace."}]},
  {id:"code",title:"Is the comment tied to the right change?",section:"Implementation · review anchor",kind:"Code and change evidence",type:"code",intro:"A code comment should retain file, revision and region identity. A later revision cannot silently transfer it to a different line.",messages:[{who:"Agent",at:"r03",text:"This curated excerpt shows the region-key change. Context outside the excerpt is not presented as reviewed."}]},
  {id:"ui",title:"Does the narrow layout keep context?",section:"Interface · responsive states",kind:"UI / UX review",type:"ui",intro:"On a narrow screen, topic and context follow a predictable drill-in. The return control goes back to the same thread and retains its draft.",messages:[{who:"Agent",at:"r03",text:"The two published states below are illustrative mockups, not screenshots from a working product."}]},
  {id:"validation",title:"What does the evidence actually prove?",section:"Validation · review outcomes",kind:"Validation evidence",type:"validation",intro:"Passing deterministic checks establish behavior within their scope. They do not imply a human accepted the interaction quality.",messages:[{who:"Agent",at:"r03",text:"The example check results and completion measures are sample evidence; no live telemetry is connected."}]},
  {id:"api",title:"What shape is published evidence?",section:"API contract · preview",kind:"Inspectable preview",type:"api",intro:"A compact contract preview exposes the revision and anchor identities without pretending this browser edits source documents.",messages:[]}
];
const state={selected:"revision",resolved:new Set(["api"]),deferred:new Set(),inspected:false,applied:false,decision:null,batch:[],drafts:{},zoom:1,step:0,node:0,filter:"all",doneOpen:false,focus:false};
const $=id=>document.getElementById(id);
const safe=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);
const item=()=>topics.find(t=>t.id===state.selected);
let toastTimer;
function toast(message){const box=$("toast");box.textContent=message;box.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.hidden=true,4200)}
function actionData(){const ready=[];if(!state.applied)ready.push({id:"revision",verb:state.inspected?"Apply inspected revision":"Inspect proposed revision",reason:"r04 changes the review path; compare before applying.",impact:"Blocks approval"});if(!state.decision)ready.push({id:"choice",verb:"Compare and decide",reason:"Choose how evidence stays linked to the thread.",impact:"Blocks approval"});if(state.batch.some(x=>x.stale&&!x.checked))ready.push({id:state.batch.find(x=>x.stale&&!x.checked).id,verb:"Recheck older comment",reason:"Its original anchor predates the applied update.",impact:"Blocks delivery"});if(!state.deferred.has("journey"))ready.push({id:"journey",verb:"Inspect reviewer journey",reason:"Check the claimed benefit against its source.",impact:"Can defer"});const waiting=[{id:"diagram",verb:"Await boundary evidence",reason:"Agent explanation is pending on this topic.",impact:"No action yet"}];const done=[];if(state.applied)done.push({id:"revision",verb:"Revision applied",reason:"r04 applied after inspection. Not approved.",impact:"Completed"});if(state.decision)done.push({id:"choice",verb:"Decision recorded",reason:state.decision+" · sample only.",impact:"Completed"});if(state.deferred.has("journey"))done.push({id:"journey",verb:"Journey deferred",reason:"Topic remains open and discoverable.",impact:"Deferred"});return{ready,waiting,done}}
function renderQueue(){const {ready,waiting,done}=actionData();$("ready-count").textContent=ready.length;$("done-count").textContent=done.length;for(const [id,items] of [["ready",ready],["waiting",waiting],["done",done]]){$(id).innerHTML=items.map(x=>`<button type="button" class="action-card ${state.selected===x.id?"selected":""}" data-topic="${safe(x.id)}"><span class="action-verb">${safe(x.verb)}<span class="arrow">↗</span></span><span class="action-subject">${safe(topics.find(t=>t.id===x.id)?.title||x.id)}</span><span class="action-reason">${safe(x.reason)}</span><span class="impact ${x.impact==="Can defer"||x.impact==="No action yet"||x.impact==="Completed"||x.impact==="Deferred"?"neutral":""}">${safe(x.impact)}</span></button>`).join("")}$("done").hidden=!state.doneOpen;$("done-toggle").setAttribute("aria-expanded",String(state.doneOpen))}
function renderTopics(){for(const [id,list] of [["topics-active",topics.filter(t=>!state.resolved.has(t.id))],["topics-resolved",topics.filter(t=>state.resolved.has(t.id))]])$(id).innerHTML=list.map(t=>`<button type="button" class="topic-button" data-topic="${safe(t.id)}" aria-current="${t.id===state.selected}"><span class="topic-glyph" aria-hidden="true">${state.resolved.has(t.id)?"✓":"◇"}</span><span><strong>${safe(t.title)}</strong><small>${safe(t.section)} · ${t.id==="revision"&&!state.applied?"proposed r04":"r03"}</small></span></button>`).join("");$("topic-count").textContent=topics.length}
function renderDiscussion(){const t=item();$("topic-title").textContent=t.title;$("topic-revision").textContent=t.id==="revision"&&!state.applied?"r04 proposed":"r03";$("subject-link").textContent=t.section;$("conversation").innerHTML=`<p class="statement">${safe(t.intro)}</p><div class="recommendation"><div class="label-row">AGENT RECOMMENDATION · NOT YOUR DECISION</div><p>${t.id==="choice"?"Keep evidence beside the conversation, with an explicit focused reading mode for dense material.":t.id==="revision"?"Inspect the changed subjects, then explicitly apply r04 if it reflects your intent.":"Inspect the supplied evidence and ask about any unsupported assumptions."}</p></div>`;
$("choice-panel").innerHTML=t.id==="choice"?`<div class="label-row">CONSEQUENTIAL CHOICE</div><div class="choice-card recommended"><span class="tag">RECOMMENDED</span><h3>Linked side canvas</h3><p>Preserves the question and reading position. Costs horizontal space; narrow screens need a drill-in.</p></div><div class="choice-card"><h3>Separate reading page</h3><p>More room for dense evidence, but the thread disappears. A back path must recover context and drafts.</p></div><div class="choice-actions"><button class="primary" data-choice="Linked side canvas" ${state.decision?"disabled":""}>Choose linked canvas</button><button class="secondary" data-choice="Separate reading page" ${state.decision?"disabled":""}>Choose reading page</button></div>${state.decision?`<p class="source">Your sample decision: ${safe(state.decision)}. Recorded separately from the agent recommendation.</p>`:""}`:t.id==="revision"?`<div class="choice-actions"><button class="secondary" data-inspect="1">${state.inspected?"✓ Inspected changes":"Inspect changes"}</button><button class="primary" data-apply="1" ${!state.inspected||state.applied?"disabled":""}>${state.applied?"Applied · not approved":"Apply r04"}</button></div>`:t.id==="journey"?`<div class="choice-actions"><button class="secondary" data-defer="journey" ${state.deferred.has("journey")?"disabled":""}>Defer nonblocking action</button></div>`:"";
const entries=[...t.messages,...(t.localMessages||[])];$("thread-count").textContent=entries.length+" replies";$("messages").innerHTML=entries.map(m=>`<article class="message ${m.who==="You"?"human":""}"><div class="message-head"><span class="avatar">${m.who==="You"?"Y":"A"}</span><strong>${safe(m.who)}</strong><small>· ${safe(m.at)}</small></div><p>${safe(m.text)}</p></article>`).join("")||`<p class="lead">No replies yet. Start this topic's discussion.</p>`;
$("comment").value=state.drafts[t.id]||"";$("resolve").textContent=state.resolved.has(t.id)?"↶ Reopen topic":"✓ Resolve topic";$("draft-hint").textContent="Draft stays in this preview"}
function card(title,body){return `<div class="evidence-box"><strong>${title}</strong><p>${body}</p></div>`}
function canvasHTML(t){switch(t.type){case "revision":return `<div class="eyebrow">BEFORE / PROPOSED · SAMPLE CONTENT</div><p class="lead">r04 awaits inspection and explicit application. Changed subjects are shown here instead of two unstructured documents.</p><div class="compare"><div class="compare-card"><div class="label-row">CURRENT · r03</div><strong>Context behind a tab</strong><p>Find a section, then navigate to the related discussion. A response can drift away from its evidence.</p></div><div class="compare-card chosen"><div class="label-row">PROPOSED · r04</div><strong>Topic and evidence side by side</strong><p>Start with an actionable question. Inspect the cited source without leaving its thread.</p></div></div><div class="evidence-label">AFFECTED SUBJECTS</div>${card("Interaction model","Reframes context navigation and the narrow-screen return path.")}${card("Decision authority","Clarifies that applying a revision does not decide or approve it.")}<div class="choice-actions"><button class="secondary" data-inspect="1">${state.inspected?"✓ Changes inspected":"Mark changes inspected"}</button><button class="primary" data-apply="1" ${!state.inspected||state.applied?"disabled":""}>${state.applied?"Applied · not approved":"Apply proposed revision"}</button></div>`;
case "journey":{const steps=[{title:"Find the question",detail:"Action queue names the subject and why it matters now.",source:"Reviewer interview note · sample · 2025-04",quote:"I know there is a change, but not which question I need to answer first."},{title:"Follow the source",detail:"Open the exact evidence next to the selected discussion.",source:"Journey walkthrough · sample · r03",quote:"The topic remains visible when I inspect the supporting artifact."},{title:"Make a decision",detail:"Compare consequences, record a choice, see the next action.",source:"Acceptance scenario · sample · r03",quote:"Applying a new document version must not be mistaken for approving it."}];const s=steps[state.step];return `<h3>From orientation to decision</h3><p class="lead">Before: scan the artifact, hunt for an outstanding question. After: take a named action, inspect its source, return to the same thread.</p><div class="metric-strip"><div class="metric"><strong>3 steps</strong><span>Published example journey</span></div><div class="metric"><strong>1 path</strong><span>Question → source → choice</span></div><div class="metric"><strong>Not measured</strong><span>No live product metric supplied</span></div></div><div class="evidence-label">SELECT A STEP</div><div class="journey">${steps.map((x,i)=>`<button type="button" class="journey-step ${i===state.step?"active":""}" data-step="${i}"><b>0${i+1}</b><strong>${x.title}</strong><small>${x.detail}</small></button>`).join("")}</div>${card("Evidence for step 0"+(state.step+1),`“${s.quote}”<div class="source">${s.source}</div>`)}<p class="source">Limit: these are illustrative supplied claims, not validated user research.</p>`}
case "choice":return `<h3>Two ways to keep evidence in reach</h3><p class="lead">The recommendation is agent-owned. Only the explicit choice in the conversation records the human's decision.</p><div class="compare"><div class="compare-card chosen"><div class="label-row">OPTION A · RECOMMENDED</div><strong>Linked canvas</strong><p>Benefit: conversation and context remain together.</p><p>Tradeoff: narrow layouts need a clear drill-in and return route.</p><p>Consequence: selected topic drives the canvas; full artifact remains one action away.</p></div><div class="compare-card"><div class="label-row">OPTION B</div><strong>Separate reading page</strong><p>Benefit: more area for long documents.</p><p>Tradeoff: users must reconstruct their place in the discussion.</p><p>Consequence: return state and draft recovery become critical.</p></div></div>${card("Assumption to check","The human reviews multiple sources while drafting a response. Ask in the linked topic if that assumption is wrong.")}`;
case "diagram":return `<h3>Published evidence flow</h3><p class="lead">Select a node or follow the text outline. Zoom is local to this published diagram and does not invoke the agent.</p><div class="zoom-tools"><button class="secondary" data-zoom="out" aria-label="Zoom out">−</button><span>${Math.round(state.zoom*100)}%</span><button class="secondary" data-zoom="in" aria-label="Zoom in">+</button><button class="secondary" data-zoom="reset">Reset</button></div><div class="diagram-wrap"><div class="diagram" style="transform:scale(${state.zoom});height:${Math.max(140,160*state.zoom)}px">${["Agent publishes","Local store","Browser reads","Human decides"].map((x,i)=>`${i?'<span class="edge" aria-hidden="true">→</span>':""}<button class="node ${state.node===i?"active":""}" data-node="${i}">${x}</button>`).join("")}</div></div><div class="evidence-label">TEXT OUTLINE</div><div class="outline">${["Agent publishes","Local store","Browser reads","Human decides"].map((x,i)=>`<button data-node="${i}">${i+1}. ${x}</button>`).join("")}</div>${card(["Agent publishes","Local store","Browser reads","Human decides"][state.node],["Versioned evidence enters the local workspace. Untrusted content is kept inert.","The private store binds evidence, revision, comments and approval target.","Same-origin local page reads published evidence. An isolated prototype has no workspace credentials.","A human explicitly inspects, applies and decides. No canvas interaction grants approval."][state.node])}`;
case "code":return `<h3>Curated region · anchor.ts</h3><p class="lead">Example diff at revision r03. Select a line to open a region-linked discussion. This is not a repository browser.</p><div class="code" role="group" aria-label="Sample code change"><span class="code-line" tabindex="0" data-line="17"><span class="ln">17</span>function anchor(comment, region) {</span><span class="code-line del" tabindex="0" data-line="18"><span class="ln">18</span>-  return region.line</span><span class="code-line add" tabindex="0" data-line="19"><span class="ln">19</span>+  return [comment.revision, region.id]</span><span class="code-line" tabindex="0" data-line="20"><span class="ln">20</span>}</span></div>${card("Source identity","anchor.ts · curated lines 17–20 · sample revision r03. Omitted surrounding context has not been reviewed.")}<p class="source">Select a line with mouse or keyboard to discuss its region. A changed revision requires anchor recheck.</p>`;
case "ui":return `<h3>Published responsive states</h3><p class="lead">These are illustrative state mockups, not captured screenshots. Select a panel for contextual annotation.</p><div class="split-ui"><div class="ui-frame"><span>BEFORE · narrow</span><button data-region="Before: context hidden behind tabs"><div class="ui-mini"><strong>Artifact</strong><div class="line"></div><div class="line short"></div><div class="line"></div><div class="chip">Conversation tab →</div></div></button></div><div class="ui-frame"><span>PROPOSED · narrow</span><button data-region="Proposed: return to the same thread"><div class="ui-mini"><strong>Question → Context</strong><div class="chip">← Back to topic</div><div class="line short"></div><div class="line"></div><div class="line short"></div></div></button></div></div>${card("Interaction state","A draft remains in its topic when context opens and when the reader returns. Try the narrow layout by resizing the window.")}`;
case "validation":{const results=[{name:"Approval target fingerprint",status:"Pass",scope:"Candidate identity only"},{name:"Stale anchor recheck",status:"Pass",scope:"Draft remains unsent"},{name:"Visual acceptance",status:"Not supplied",scope:"Requires human assessment"}].filter(x=>state.filter==="all"|| (state.filter==="gaps"?x.status!=="Pass":x.status==="Pass"));return `<h3>Checks are not blanket approval</h3><p class="lead">Example evidence only, from a bounded run. Filter the supplied results; there is no live telemetry.</p><div class="filter-row"><button data-filter="all" class="${state.filter==="all"?"active":""}">All</button><button data-filter="pass" class="${state.filter==="pass"?"active":""}">Passing</button><button data-filter="gaps" class="${state.filter==="gaps"?"active":""}">Gaps</button></div><div class="bars"><div class="bar" style="height:40%"><span>2</span></div><div class="bar after" style="height:65%"><span>3</span></div></div><div class="bar-labels"><span>Before: scoped checks</span><span>After: scoped checks</span></div><div class="evidence-label">RESULT DETAILS</div><table class="table"><thead><tr><th>Check</th><th>Result</th><th>Limit</th></tr></thead><tbody>${results.map(x=>`<tr><td>${x.name}</td><td class="${x.status==="Pass"?"status-pass":"status-gap"}">${x.status}</td><td>${x.scope}</td></tr>`).join("")}</tbody></table><p class="source">Sample run · r03 · no time-series data or live dashboard supplied.</p>`}
case "api":return `<h3>Versioned evidence envelope</h3><p class="lead">Inspectable preview. Source access remains available when supplied; this sample offers no live editing or external connection.</p><div class="code"><span class="code-line">{ "revision": "r03",</span><span class="code-line">  "subject": "journey",</span><span class="code-line">  "region": "step-follow-source" }</span></div>${card("Change rule","If a new revision cannot match this identity, a pending comment remains unsent until explicitly rechecked.")}`;
}}
function renderCanvas(){const t=item();$("canvas-kind").textContent=t.kind;$("canvas-title").textContent=t.section;$("canvas-source").textContent=`Source: published example · ${t.id==="revision"&&!state.applied?"r04 proposed":"r03"} · ${t.type}`;$("canvas-content").innerHTML=canvasHTML(t)}
function renderReview(){const {ready}=actionData();const blockers=ready.filter(x=>x.impact==="Blocks approval"||x.impact==="Blocks delivery");$("review-stats").textContent=`${state.batch.length} pending comment${state.batch.length===1?"":"s"} · ${topics.length-state.resolved.size} open topic${topics.length-state.resolved.size===1?"":"s"} · ${blockers.length} blocker${blockers.length===1?"":"s"}. Open topics alone do not block approval.`;$("batch").innerHTML=state.batch.map((x,i)=>`<div class="batch-item"><span>${safe(topics.find(t=>t.id===x.id)?.title||x.id)} · ${x.stale?`<span class="stale">Older r03 anchor ${x.checked?"rechecked":"needs recheck"}</span>`:"r03"}<br>${safe(x.text)}</span><span><button data-edit-batch="${i}" type="button">Edit</button>${x.stale&&!x.checked?`<button data-recheck="${i}" type="button">Recheck</button>`:""}<button data-remove-batch="${i}" type="button">Remove</button></span></div>`).join("");const canApprove=state.applied&&!!state.decision&&!state.batch.some(x=>x.stale&&!x.checked);$("approve-hint").textContent=canApprove?"Available in this sample. Exact target r04; no phase starts.":"Unavailable: inspect/apply r04, resolve consequential choice and recheck stale comments.";$("review-form").elements.outcome.forEach(x=>{if(x.value==="approve")x.disabled=!canApprove});if(!canApprove&&$("review-form").elements.outcome.value==="approve")$("review-form").elements.outcome.value="comment"}
function render(){renderQueue();renderTopics();renderDiscussion();renderCanvas();renderReview()}
function select(id){if(!topics.some(t=>t.id===id))return;state.drafts[state.selected]=$("comment").value;state.selected=id;state.step=0;state.node=0;render();if(window.innerWidth<=850)document.querySelector(".discussion").scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth",block:"start"})}
function addMessage(text,at){const t=item();t.localMessages??=[];t.localMessages.push({who:"You",at,text});state.drafts[t.id]="";render()}
function saveDraft(){state.drafts[state.selected]=$("comment").value}
function confirmChoice(value){if(!window.confirm(`Record sample choice: ${value}? This is a preview and does not decide in the real workspace.`))return;state.decision=value;render();toast("Sample choice recorded separately from the recommendation.")}
function apply(){if(!state.inspected||state.applied)return;if(!window.confirm("Apply example r04? Applying is not approval. Existing unsent comments retain their older anchors."))return;state.applied=true;state.batch.forEach(x=>{x.stale=true;x.checked=false});render();toast("Example revision applied. Earlier comments now require recheck.")}
function openReview(){renderReview();$("review-dialog").showModal()}
document.addEventListener("click",event=>{const target=event.target.closest("[data-topic],[data-choice],[data-inspect],[data-apply],[data-defer],[data-step],[data-node],[data-zoom],[data-line],[data-region],[data-filter],[data-edit-batch],[data-remove-batch],[data-recheck]");if(!target)return;
if(target.dataset.topic)select(target.dataset.topic);
if(target.dataset.choice)confirmChoice(target.dataset.choice);
if(target.dataset.inspect){state.inspected=true;render();toast("Changed subjects inspected. You can now apply r04.")}
if(target.dataset.apply)apply();
if(target.dataset.defer){state.deferred.add(target.dataset.defer);render();toast("Action deferred. The underlying topic remains open.")}
if(target.dataset.step!==undefined){state.step=Number(target.dataset.step);renderCanvas()}
if(target.dataset.node!==undefined){state.node=Number(target.dataset.node);renderCanvas()}
if(target.dataset.zoom){state.zoom=target.dataset.zoom==="reset"?1:Math.max(.7,Math.min(1.5,state.zoom+(target.dataset.zoom==="in"?.15:-.15)));renderCanvas()}
if(target.dataset.line){toast(`Sample region anchor: anchor.ts · r03 · line ${target.dataset.line}. Continue discussion in the selected topic.`);$("comment").focus()}
if(target.dataset.region){toast(`Sample annotation: ${target.dataset.region}`);$("comment").focus()}
if(target.dataset.filter){state.filter=target.dataset.filter;renderCanvas()}
if(target.dataset.editBatch!==undefined){const [x]=state.batch.splice(Number(target.dataset.editBatch),1);$("review-dialog").close();select(x.id);$("comment").value=x.text;saveDraft();$("comment").focus();toast("Pending comment moved to its topic for editing.")}
if(target.dataset.removeBatch!==undefined){state.batch.splice(Number(target.dataset.removeBatch),1);render();toast("Pending comment removed.")}
if(target.dataset.recheck!==undefined){state.batch[Number(target.dataset.recheck)].checked=true;render();toast("Sample anchor explicitly rechecked; delivery remains a separate action.")}
});
document.addEventListener("keydown",event=>{if((event.key==="Enter"||event.key===" ")&&event.target.matches(".code-line[data-line]")){event.preventDefault();event.target.click()}if(event.key==="Escape"&&state.focus){state.focus=false;document.body.classList.remove("focus-mode");$("focus").setAttribute("aria-label","Focus canvas")}});
$("comment").addEventListener("input",saveDraft);
$("send").onclick=()=>{const text=$("comment").value.trim();if(!text)return toast("Write a comment first.");addMessage(text,"sample · not sent");toast("Comment added to this preview only; no agent request was sent.")};
$("hold").onclick=()=>{const text=$("comment").value.trim();if(!text)return toast("Write a comment first.");state.batch.push({id:state.selected,text,stale:state.applied,checked:!state.applied});state.drafts[state.selected]="";render();toast("Unsent comment added to the sample review batch.")};
$("resolve").onclick=()=>{const id=state.selected;if(state.resolved.has(id))state.resolved.delete(id);else state.resolved.add(id);render();toast(state.resolved.has(id)?"Topic explicitly resolved, independent of approval.":"Topic reopened and returned to active topics.")};
$("theme").onclick=()=>{const dark=document.documentElement.dataset.theme!=="dark";document.documentElement.dataset.theme=dark?"dark":"light";$("theme").setAttribute("aria-label",`Switch to ${dark?"light":"dark"} mode`)};
$("done-toggle").onclick=()=>{state.doneOpen=!state.doneOpen;renderQueue()};
$("submit-top").onclick=openReview;
$("show-context").onclick=$("context-mobile").onclick=()=>{document.querySelector(".shell").classList.add("context-open");$("back-mobile").focus()};
$("back-mobile").onclick=()=>{document.querySelector(".shell").classList.remove("context-open");$("context-mobile").focus()};
$("full-artifact").onclick=()=>$("artifact-dialog").showModal();
$("artifact-close").onclick=$("artifact-back").onclick=()=>$("artifact-dialog").close();
$("focus").onclick=()=>{state.focus=!state.focus;document.body.classList.toggle("focus-mode",state.focus);$("focus").setAttribute("aria-label",state.focus?"Exit focused canvas":"Focus canvas")};
$("comment-context").onclick=()=>{document.querySelector(".shell").classList.remove("context-open");if(state.focus){state.focus=false;document.body.classList.remove("focus-mode")}$("comment").focus()};
$("review-form").addEventListener("submit",event=>{if(event.submitter?.value!=="submit")return;const outcome=$("review-form").elements.outcome.value,summary=$("review-summary").value.trim();if(outcome==="changes"&&!summary){event.preventDefault();toast("Describe the required changes first.");$("review-summary").focus();return}if(state.batch.some(x=>x.stale&&!x.checked)){event.preventDefault();toast("Recheck older anchors before delivering the batch.");return}if(outcome==="approve"&&(!state.applied||!state.decision)){event.preventDefault();toast("Approval is unavailable while blockers remain.");return}if(outcome==="approve"&&!window.confirm("Confirm sample approval of r04? This preview cannot approve the real spec.")){event.preventDefault();return}event.preventDefault();$("review-dialog").close();const count=state.batch.length;state.batch=[];render();toast(`Sample ${outcome} outcome with ${count} comment${count===1?"":"s"} previewed. Nothing was delivered.`)});
render();
