import { X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Prose } from "@/components/prose"
import type { Decision, Discussion, Document } from "@/lib/workspace"
import type { Depth } from "./decision-packet"
import { useEffect, useRef, type RefObject } from "react"

const names = { why: "Why this matters", architecture: "How this works", evidence: "Evidence", code: "Relevant code", discussion: "Discussion", artifact: "Full artifact" }
export function ContextDrawer({ view, close, decision, current, messages, version, draft, draftVersion, changeDraft, reanchor, send, busy, active, editor }: { view: NonNullable<Depth>; close: () => void; decision?: Decision; current?: Document; messages: Discussion[]; version: string; draft: string; draftVersion: string; changeDraft: (value: string) => void; reanchor: () => void; send: (event: React.FormEvent) => void; busy: boolean; active: boolean; editor: RefObject<HTMLTextAreaElement | null> }) {
  const title = useRef<HTMLHeadingElement>(null)
  useEffect(() => { if (view !== "discussion") title.current?.focus() }, [view])
  return <section className="context-panel" aria-label={names[view]}><header className="flex items-center justify-between border-b px-5 py-4"><h2 ref={title} tabIndex={-1} className="text-base font-semibold outline-none">{names[view]}</h2><button className="icon-button" aria-label="Close context" onClick={close}><X size={18}/></button></header><div className="context-panel-content">
    {view === "why" && <><p className="eyebrow">MINIMUM MENTAL MODEL</p><p>{decision?.context?.mentalModel || decision?.context?.explanation || decision?.consequence || "Published revisions must be inspected and applied separately from final approval."}</p>{decision?.context?.explanation && decision.context.mentalModel && <><p className="eyebrow">WHY IT MATTERS</p><p>{decision.context.explanation}</p></>}{decision?.context?.remember && <div className="border-t pt-4"><p className="eyebrow">WHAT TO REMEMBER</p><p className="mt-2">{decision.context.remember}</p></div>}</>}
    {view === "architecture" && <><p className="eyebrow">SYSTEM RELATIONSHIP</p><p>{decision?.context?.architecture || "The published artifact is bound to one exact version."}</p>{decision?.context?.remember && <p className="border-t pt-4">{decision.context.remember}</p>}</>}
    {view === "evidence" && <>{decision?.context?.evidence?.length ? decision.context.evidence.slice(0, 5).map((entry, index) => <section key={index} className="border-b pb-4">{typeof entry === "string" ? <Prose text={entry}/> : <><h3 className="font-medium">{entry.label || "Evidence"}</h3><p className="mt-1">{entry.summary}</p>{entry.source && <p className="mt-2 text-xs text-muted-foreground">{entry.source}</p>}</>}</section>) : <p>No item-specific evidence was published. Ask the agent before relying on an unsupported claim.</p>}</>}
    {view === "code" && <>{decision?.context?.code?.length ? decision.context.code.map((entry, index) => <section key={index} className="border-b pb-4">{typeof entry === "string" ? <Prose text={entry}/> : <><h3 className="break-all font-mono text-xs">{entry.path || entry.symbol || "Relevant code"}{entry.lines && `:${entry.lines}`}</h3><p className="mt-2">{entry.summary}</p>{entry.excerpt && <pre className="mt-3 overflow-x-auto rounded-md bg-muted p-3 text-xs"><code>{entry.excerpt}</code></pre>}</>}</section>) : <p>No code excerpt was published for this decision.</p>}</>}
    {view === "artifact" && <>{current?.markdown ? <Prose text={current.markdown}/> : <><Prose text={current?.recommendation || "No artifact published."}/>{current?.sections.map(section => <section key={section.id} className="border-t pt-4"><h3 className="font-medium">{section.title}</h3><Prose text={section.body}/></section>)}</>}</>}
    {view === "discussion" && <><div className="divide-y border-y" aria-label="Discussion on this item">{messages.length ? messages.map(message => <div key={message.id} className="py-3"><p className="text-xs text-muted-foreground"><strong>{message.author === "human" ? "You" : "Agent"}</strong> · {message.version === version ? "Current revision" : `Earlier revision ${message.version.slice(0, 8)}`} {message.status && `· ${message.status}`}</p><div className="mt-1"><Prose text={message.text}/></div></div>) : <p className="py-3 text-muted-foreground">No discussion yet.</p>}</div><form onSubmit={send} className="space-y-3"><label htmlFor="context-question" className="font-medium">Ask the agent about this exact context</label><Textarea id="context-question" ref={editor} value={draft} onChange={event => changeDraft(event.target.value)} maxLength={20000} rows={4}/><p className="text-xs text-muted-foreground">Draft saved locally. Replies never resolve a decision automatically.</p>{draft && draftVersion !== version && <div className="border-l-2 pl-3">This draft belongs to revision {draftVersion.slice(0, 8)}. Inspect this new revision before sending. <Button type="button" size="sm" variant="outline" onClick={reanchor}>I rechecked this anchor</Button></div>}<Button type="submit" disabled={!active || busy || !draft.trim() || draftVersion !== version}>Send to agent</Button></form></>}
  </div></section>
}
