import { ArrowRight } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Prose } from "@/components/prose"
import type { Document } from "@/lib/workspace"

export function RevisionPacket({ current, pending, inspected, onInspect, apply, disabled }: { current?: Document; pending: Document; inspected: string[]; onInspect: (id: string) => void; apply: () => void; disabled: boolean }) {
  const changed = pending.sections.filter(section => !current?.sections.some(old => old.id === section.id && old.title === section.title && old.body === section.body))
  const removed = current?.sections.filter(section => !pending.sections.some(next => next.id === section.id)) || []
  const recommendation = current?.recommendation !== pending.recommendation
  const decisions = JSON.stringify(current?.decisions) !== JSON.stringify(pending.decisions)
  const ids = [...changed.map(s => `section:${s.id}`), ...removed.map(s => `removed:${s.id}`), ...(recommendation ? ["recommendation"] : []), ...(decisions ? ["decisions"] : [])]
  if (!ids.length) ids.push("artifact")
  const ready = ids.every(id => inspected.includes(id))
  return <div className="mt-8 space-y-5"><p className="text-base leading-7">The agent published a new revision. Inspect the changed subjects before applying it. Application does not approve the target.</p><div className="flow" aria-label="Current revision, inspect proposed revision, apply, review"><span>Current {current?.version.slice(0, 8) || "none"}</span><ArrowRight size={16}/><span>Inspect {pending.version.slice(0, 8)}</span><ArrowRight size={16}/><span>Apply</span><ArrowRight size={16}/><span>Review</span></div>
  <div className="space-y-2" aria-label="Changed subjects">{recommendation && <details className="revision-subject" onToggle={event => { if (event.currentTarget.open) onInspect("recommendation") }}><summary>Changed recommendation {inspected.includes("recommendation") ? "✓" : ""}</summary><p className="mt-3 text-muted-foreground">Before: {current?.recommendation || "None"}</p><div className="mt-2"><Prose text={pending.recommendation}/></div></details>}
  {changed.map(section => <details key={section.id} className="revision-subject" onToggle={event => { if (event.currentTarget.open) onInspect(`section:${section.id}`) }}><summary>{section.title} {inspected.includes(`section:${section.id}`) ? "✓" : ""}</summary>{current?.sections.find(old => old.id === section.id) && <div className="mt-3 border-l-2 pl-3 text-muted-foreground"><p className="eyebrow">BEFORE</p><Prose text={current.sections.find(old => old.id === section.id)!.body}/></div>}<div className="mt-3 border-l-2 border-foreground pl-3"><p className="eyebrow">PROPOSED</p><Prose text={section.body}/></div></details>)}
  {removed.map(section => <details key={section.id} className="revision-subject" onToggle={event => { if (event.currentTarget.open) onInspect(`removed:${section.id}`) }}><summary>Removed: {section.title} {inspected.includes(`removed:${section.id}`) ? "✓" : ""}</summary><Prose text={section.body}/></details>)}
  {decisions && <details className="revision-subject" onToggle={event => { if (event.currentTarget.open) onInspect("decisions") }}><summary>Decisions added or changed {inspected.includes("decisions") ? "✓" : ""}</summary><ul className="mt-3 space-y-3">{pending.decisions.map(decision => <li key={decision.id}><strong>{decision.subject}</strong><p>{decision.recommendation}</p><small>{decision.consequence}</small></li>)}</ul>{!pending.decisions.length && <p className="mt-3">No decisions in proposed revision.</p>}</details>}
  {!changed.length && !removed.length && !recommendation && !decisions && <details className="revision-subject" onToggle={event => { if (event.currentTarget.open) onInspect("artifact") }}><summary>Inspect proposed artifact</summary><div className="mt-3"><Prose text={pending.markdown || pending.sections.map(s => `## ${s.title}\n${s.body}`).join("\n\n")}/></div></details>}
  </div><Button disabled={!ready || disabled} onClick={apply}>Apply inspected revision <ArrowRight size={15}/></Button>{!ready && <p className="text-xs text-muted-foreground">Open each changed subject to enable application.</p>}<details className="border-t pt-4"><summary className="cursor-pointer">Full proposed artifact</summary><div className="mt-4"><Prose text={pending.markdown || pending.sections.map(s => `## ${s.title}\n${s.body}`).join("\n\n")}/></div></details></div>
}
