#!/usr/bin/env python3

import json
import subprocess
import sys

CONFIG_DIR="/root/config/dev"
BUILD_FILE=CONFIG_DIR + "/build.json"

def run_cmd(command):
    print(f"running: {command}")
    p = subprocess.run(command, shell=True, stdout=sys.stdout, stderr=sys.stderr)

    if p.returncode != 0:
        sys.exit(p.returncode)

    return p

def step_packages(step):
    packages = step["packages"]
    cmd = "dnf install -y " + " ".join(packages) 
    run_cmd(cmd)

def step_shell(step):
    shell = step["shell"]
    cmd = " && ".join(shell)
    run_cmd(cmd)

with open(BUILD_FILE) as i:
    build_meta_raw = i.read() 

print("===================== build config =====================") 
print(build_meta_raw)
print("========================================================") 

build_meta = json.loads(build_meta_raw)
for step in build_meta:
    step_name = step["name"]
    print(step_name)
    if "packages" in step:
        step_packages(step)
    elif "shell" in step:
        step_shell(step)    
