jobs:
  link_configs:
    steps:
      - run: mkdir ~/.config
      - run: rm -rf ~/.config/nvim && ln -s ~/dev/config/nvim ~/.config/nvim
      - run: rm -rf ~/.zshrc && ln -s ~/dev/config/zsh/.zshrc ~/.zshrc
  install_editor_dependencies:
    steps:
      - run: >
          dnf install -y
          git
          nodejs
          nodejs-yarn
          neovim
          python3-neovim
          fzf
          ripgrep
  setup_editor:
    needs:
      - link_configs
      - install_editor_dependencies
    steps:
      - run: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      - run: nvim --headless +PlugInstall +qall
  install_system_dependencies:
    steps:
      - run: >
          dnf install -y
          zsh
          hub
          golang
          clang
  install_oh_my_zsh:
    needs:
      - link_configs
      - install_system_dependencies
    steps:
      - run: sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\" --unattended --skip-chsh --keep-zshrc
