import { test } from "node:test";
import assert from "node:assert/strict";
import { ShipRuntime, type ShipState } from "../lib/ship-runtime.ts";
import { role } from "../lib/roles.ts";
const oid = "a".repeat(40), candidate = { repository: { root: "/r", coordinate: "github.com/o/r" }, worktree: "/r", branch: { name: "f", head: oid }, base: { ref: "main", oid: "b".repeat(40) }, remote: { name: "origin", url: "https://github.com/o/r.git", oid: "b".repeat(40) } } as const;
const handoff = { version: 2 as const, candidate, approved: { spec: { path: "s", sha256: "c".repeat(64) }, plan: { path: "p", sha256: "d".repeat(64) } }, completedOutcomes: ["one"], localChecks: [], residualRisks: [], unresolvedDecisions: [], expectedReviewSignals: [], recordedAt: 1 };
function createRuntime() { const saved: ShipState[] = []; const state: ShipState = { invocationId: "i", revision: 0, phase: "handoff", candidate: structuredClone(candidate), handoff, repairs: 0, stableKeys: [] }; return [new ShipRuntime(state, { refresh: async x => x, persist: x => { saved.push(x); } }), saved] as const; }
test("ship runtime rejects stale actions, uses normal then escalated Builder, and enforces repair limit", async () => { const [runtime] = createRuntime(); await runtime.admit({ invocationId: "i", expectedRevision: 0, expectedCandidate: candidate, action: "prepare" }); assert.deepEqual(runtime.builderRole(), role("build")); await runtime.complete("prepare"); await assert.rejects(runtime.admit({ invocationId: "i", expectedRevision: 0, expectedCandidate: candidate, action: "publish" }), /Stale/); await runtime.complete("publish"); await runtime.complete("wait"); await runtime.complete("audit"); await runtime.complete("repair"); assert.deepEqual(runtime.builderRole(), role("escalated_builder")); await runtime.complete("prepare"); await runtime.complete("publish"); await runtime.complete("wait"); await runtime.complete("audit"); await runtime.complete("repair"); await runtime.complete("prepare"); await runtime.complete("publish"); await runtime.complete("wait"); await runtime.complete("audit"); await assert.rejects(runtime.complete("repair"), /two-round/); });
test("worker-backed transitions reserve their revision and complete or fail only the exact job", async () => {
  const [runtime,saved] = createRuntime();
  await runtime.admit({ invocationId: "i", expectedRevision: 0, expectedCandidate: candidate, action: "prepare" });
  const reserved = await runtime.reserveWorker("job:1", "prepare", "Builder");
  assert.equal(reserved.revision,1); assert.equal(reserved.pendingWorker?.operationId,"job:1");
  await assert.rejects(runtime.admit({ invocationId: "i", expectedRevision: 1, expectedCandidate: candidate, action: "prepare" }),/still running/);
  await assert.rejects(runtime.completeWorker("job:2",{}),/Stale ship worker completion/);
  const completed = await runtime.completeWorker("job:1",{ localChecks: [] });
  assert.equal(completed.phase,"prepared"); assert.equal(completed.revision,2); assert.equal(completed.pendingWorker,undefined);

  const failedRuntime = new ShipRuntime({ ...saved[0]!, revision: 1 }, { refresh: async x=>x, persist: ()=>undefined });
  const failed = await failedRuntime.failWorker("job:1",new Error("builder failed"),7);
  assert.equal(failed.phase,"stopped"); assert.equal(failed.workerFailure?.message,"builder failed"); assert.equal(failed.pendingWorker,undefined);
});
test("repair convergence records stable keys and rejects a returning finding", async () => { const [runtime] = createRuntime(); const inventory = { candidate, digest: "e".repeat(64), items: [] }; const review = { verdict: "REPAIRS" as const, candidate, inventoryDigest: inventory.digest, dispositions: [], findings: [{ key: "same", evidence: ["path:1"], acceptanceChecks: ["test"] }], blocker: null }; const audited = await runtime.complete("audit", { inventory, reviewer: review }); assert.deepEqual(audited.stableKeys, ["same"]); assert.throws(() => runtime.validateReview(inventory, review), /returned/); assert.throws(() => runtime.validateReview(inventory, { ...review, findings: [{ ...review.findings[0]!, key: "new", evidence: [] }] }), /evidence/); });
test("candidate changes invalidate evidence and reviews require an exact disposition set", async () => { const [runtime] = createRuntime(); const inventory = { candidate, digest: "e".repeat(64), items: [{ id: "one", kind: "comment" as const, head: oid, state: "OPEN", digest: "f".repeat(64) }] }; assert.throws(() => runtime.validateReview(inventory, { verdict: "PASS", candidate, inventoryDigest: inventory.digest, dispositions: [], findings: [], blocker: null }), /exactly/); await runtime.complete("start", { inventory, approval: { packetHash: "e".repeat(64), approvedAt: 1, approver: "u" } }); const changed = { ...candidate, branch: { ...candidate.branch, head: "c".repeat(40) } }; const next = await runtime.complete("prepare", { candidate: changed }); assert.equal(next.inventory, undefined); assert.equal(next.approval, undefined); });
